### ISSUE TITLE
Yarn install fails sometimes

### ISSUE THREAD

**Issue by mraible** [mshima/jhipster-microfrontend#1]
I tried this today and found the first time I ran `yarn install` on each project, it failed.

```
[7/9] ⠠ @fortawesome/free-solid-svg-icons
warning Error running install script for optional dependency: "/Users/mraible/dev/jhipster-microfrontend/blog/node_modules/webpack-dev-server/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/mraible/dev/jhipster-microfrontend/blog/node_modules/webpack-dev-server/node_modules/fsevents
Output:
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
✨  Done in 152.83s.
Execution time: 2 min. 34 s.
```

Running it again in the blog project fixed the problem.

In the `gateway` project, the error is:

```
[7/11] ⠈ @fortawesome/free-solid-svg-icons
warning Error running install script for optional dependency: "/Users/mraible/dev/jhipster-microfrontend/gateway/node_modules/webpack-dev-server/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/mraible/dev/jhipster-microfrontend/gateway/node_modules/webpack-dev-server/node_modules/fsevents
Output:
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn node-gyp',
[-/11] ⠠ waiting...
[11/11] ⠠ ngx-infinite-scroll
[-/11] ⠠ waiting...
[10/11] ⠠ puppeteer
^C/11] ⠠ waiting...
```

I tried `rm -rf node_modules`, but it didn't help. Same error in the next `yarn install`.

```
➜  gateway git:(main) yarn --version
1.22.10
➜  gateway git:(main) node --version
v14.15.0
```

**Comment by mshima** [comment]
Never happened to me.
You can try `npm ci` using npm 7.

**Comment by mraible** [comment]
With npm 7:

```
$ npm --version
7.5.2
```

Running `npm ci` works in the `blog` project, but not in the gateway. The gateway seems to hang here:

```
⸨                  ⸩ ⠇ reify:date-fns: timing reifyNode:node_modules/browser-sync-client/node_modules/rxjs Completed in 865
```

**Comment by mshima** [comment]
Just tried and installed correctly.
You can try to remove node_modules, node, reinstalling yarn.
